### ISSUE TITLE
Test is automatically skipped?

### ISSUE THREAD

**Issue by lodisy** [marilari88/neotest-vitest#16]
Hello,

here is my config settings with `neotest`:

basically default settings

```lua
 require("neotest").setup({
            adapters = {
                require('neotest-vitest'),
                require("neotest-dart") {
                    command = "flutter",
                    use_lsp = true,
                },
                require("neotest-rust")
            },
})
```
when I toggled the summary panel, and went down to the test file, pressed `r` to run that test file. It automatically got skipped.

Vitest is installed, I cound run `pnpm run test` without problem. Or do I need to install it globally?

![2022-12-30_18-49](https://user-images.githubusercontent.com/8101584/210062153-91e0a210-ec2d-43d8-bbf7-669f02c7facd.png)

**Comment by marilari88** [comment]
Hi @lodisy, I have no chance to test your code right now. I guess there is an issue with trying to escape </> chars. Try to remove them from the parent test.
You can also replace the parent 'test' with 'describe'.
Let me know if you manage to run your tests

**Comment by lodisy** [comment]
> Hi @lodisy, I have no chance to test your code right now. I guess there is an issue with trying to escape </> chars. Try to remove them from the parent test. You can also replace the parent 'test' with 'describe'. Let me know if you manage to run your tests

Hello, thanks for your reply. I still got this, if I understand correctly:

![2022-12-30_20-12](https://user-images.githubusercontent.com/8101584/210069104-283bf84b-3ea0-414f-aedb-660a51a3336c.png)

**Comment by marilari88** [comment]
Ok. We can exclude escaping issues.
The tree in the summary panel is clearly broken: the file name appears under describe name. Is treesitter installed with jsx/tsx parser? Is you code in public repo?

**Comment by lodisy** [comment]
> Ok. We can exclude escaping issues.
> The tree in the summary panel is clearly broken: the file name appears under describe name. Is treesitter installed with jsx/tsx parser? Is you code in public repo?

Thanks you're right.

Somehow I didn't have the tsx installed. Thought the typescript parser would have handled that.

Thanks 🙏
