### ISSUE TITLE
Tests are not run (`package.json not found`)

### ISSUE THREAD

**Issue by j-a-m-l** [marilari88/neotest-vitest#20]
When I save a file I see this message:

```
package.json not found
"tests/example.spec.ts" 7L, 100B written
Press ENTER or type command to continue
```

It happens independently of its location in the project.

The content is not relevant (I've tried with several files).

Tests are not executed when saving these files or using the summary.

**Comment by marilari88** [comment]
Hi @j-a-m-l do you have a public repo that I can test?
This error occours when the adapter cannot find a valid package.json to look into for check vitest dependency

**Comment by j-a-m-l** [comment]
Thanks, @marilari88.

I've just pushed the project to https://gitlab.com/meaningfuldata/antlr-monaco.

**Comment by boydaihungst** [comment]
@marilari88 
you should check file_path match file extension before check `hasVitestDependency`.  
init.lua
```lua
function adapter.is_test_file(file_path)
  if file_path == nil then
    return false
  end



  if string.match(file_path, "__tests__") then
    return true
  end

  for _, x in ipairs({ "spec", "test" }) do
    for _, ext in ipairs({ "js", "jsx", "coffee", "ts", "tsx" }) do
      if string.match(file_path, "%." .. x .. "%." .. ext .. "$") then
        return true
      end
    end
  end

  if not hasVitestDependency(file_path) then
    return false
  end
  return false
end

```

**Comment by marilari88** [comment]
Hi @boydaihungst! Great job!  I have sent you some comments. Thanks for your appreciated contribution!

**Comment by j-a-m-l** [comment]
Thanks @marilari88 and @boydaihungst. That has solved one of my problems.
