### ISSUE TITLE
Tests always show as failed in gutter sign and summary even though output shows passed

### ISSUE THREAD

**Issue by GitMurf** [marilari88/neotest-vitest#48]
I just installed and setup for the first time and got things seemingly working except they always show as failed even when the tests are successful. See screenshot. Any thoughts? Thanks!

![image](https://github.com/marilari88/neotest-vitest/assets/64155612/f89deff0-82fb-461b-94e7-cec96f95c449)
![image](https://github.com/marilari88/neotest-vitest/assets/64155612/5ad53dac-e146-4f79-8204-fc4056b792bc)
![image](https://github.com/marilari88/neotest-vitest/assets/64155612/b873239f-5960-4aa8-b56d-d1b2a4fc3f0a)

**Comment by GitMurf** [comment]
Could be related  to this: https://github.com/nvim-neotest/neotest-jest/issues/94

**Comment by AlansCodeLog** [comment]
I'm also getting this. I didn't change the default command so that can't be it. I do have odd names in tests, but they're clearly being matched correctly (if I only run a single test, the status updates to running before "failing" again). Neotest logs show nothing weird. Json is being outputted correctly. Very strange.

I'm using LazyVim, so next I'm going to attempt using the plugin without Lazyvim's setup just to check.

Can anyone confirm if this is working correctly for them?

**Comment by GitMurf** [comment]
> I'm using LazyVim, so next I'm going to attempt using the plugin without Lazyvim's setup just to check.

@AlansCodeLog Don't bother trying that! I failed with lazyvim at first and then tried it from scratch without lazyvim and same results 🥲

**Comment by AlansCodeLog** [comment]
I figured out what was happening in my case. I had a dynamic name for the describe blocks and obviously the algorithm to match the names must not have been able to match it exactly. Have you tried with a file with a single simple test? That's how I realized the issue.

**Comment by GitMurf** [comment]
> I figured out what was happening in my case. I had a dynamic name for the describe blocks and obviously the algorithm to match the names must not have been able to match it exactly. Have you tried with a file with a single simple test? That's how I realized the issue.

Thanks! I will give it a try. Bummer though I don't really want to rename all my tests to satisfy this plugin working. Any hunches at where this could be fixed in the code?

**Comment by GitMurf** [comment]
Curious if you have any clue if it is a neotest/vite issue? Or if it is a core neotest issue?

**Comment by kirylvarykau** [comment]
I have the same issue :( Any updates on it?

**Comment by AlansCodeLog** [comment]
@GitMurf You also had dynamic names then? I doubt there is a way to make it work because it's not possible to know what the final name (that is outputted to json by the test library then fed to the plugin) will be in cases like this:

```
it(`how do we know what ${somevar} is`, () => {...
```

**Comment by Kahitar** [comment]
I have the same issue, even though I don't use dynamic names:

![image](https://github.com/marilari88/neotest-vitest/assets/23745459/f04e9fd3-df28-4758-822c-a66cdb2a111a)
![image](https://github.com/marilari88/neotest-vitest/assets/23745459/7d98ddaf-9ef4-487c-821d-99510c8af4ce)

**Comment by Kahitar** [comment]
Yes, I'm also on Windows (10). Could very well be..

**Comment by GitMurf** [comment]
@AlansCodeLog @kirylvarykau do you also happen to be using Windows?

**Comment by juansalvatore** [comment]
I'm using macos and have the same issue @GitMurf.
How are you running the individual tests vs in the summary section?

For me this works:
`vim.api.nvim_set_keymap('n', '<leader>twr', "<cmd>lua require('neotest').run.run({ vitestCommand = 'npx vitest run' })<cr>", { desc = 'Run Watch' })`

But running from the summary section clicking "r" doesn't

**Comment by juansalvatore** [comment]
I was just able to fix this by updating my config to this:

```lua
  require('neotest').setup {
        adapters = {
          require 'neotest-jest' {
            jestCommand = 'npx vitest run',
          },
          require 'neotest-vitest' {
            vitestCommand = 'npx vitest run',
            -- Filter directories when searching for test files. Useful in large projects (see Filter directories notes).
            filter_dir = function(name, rel_path, root)
              return name ~= 'node_modules'
            end,
          },
        },
      }
```

**Comment by AlansCodeLog** [comment]
@GitMurf No, am on linux, and I have not had any issues since I changed all the dynamic names...

**Comment by AlansCodeLog** [comment]
I've found another edge case, apparently, template strings alone (no variables) can't be used either. I was working on a parser and I did not want to escape the input strings in the tests which is why they were like this. I did a little bit of digging into the code and added my own treesitter query to quickly this. I'm not sure this should be supported out of the box since the most likely reason to use template strings is variables and I doubt those can be made to work, but @marilari88 are you open to allowing adding an option for custom treesitter queries? I can do a PR.

**Comment by marilari88** [comment]
@AlansCodeLog sure you can! It is an edge case but why not support it? Thanks

**Comment by GitMurf** [comment]
> I've found another edge case, apparently, template strings alone (no variables) can't be used either. I was working on a parser and I did not want to escape the input strings in the tests which is why they were like this. I did a little bit of digging into the code and added my own treesitter query to quickly this. I'm not sure this should be supported out of the box since the most likely reason to use template strings is variables and I doubt those can be made to work, but @marilari88 are you open to allowing adding an option for custom treesitter queries? I can do a PR.

This finally makes sense! I use template strings everywhere even without variables. So this must be my issue! Thanks so much for all your digging @AlansCodeLog !

**Comment by AlansCodeLog** [comment]
No problem, here's my [fork](https://github.com/AlansCodeLog/neotest-vitest) with the option to add additional treesitter queries. Then you can do the following for now to get template string support:

```
{
	"alanscodelog/neotest-vitest",
	opts = {
		additional_treesitter_queries = [[
			((call_expression
				function: (identifier) @func_name (#any-of? @func_name "it" "test")
				arguments: (arguments (template_string (string_fragment) @test.name) (arrow_function))
			)) @test.definition
		]],
	},
},

```

**Comment by Daydreamer-riri** [comment]
Hi @marilari88 , I didn't use any template strings and still have this problem.
![image](https://github.com/user-attachments/assets/fc17c6ac-8388-49b2-8bfd-8558bab99f25)

**Comment by GitMurf** [comment]
@Daydreamer-riri are you on Windows?

**Comment by Daydreamer-riri** [comment]
> @Daydreamer-riri are you on Windows?

Yes.

**Comment by BitsAndDroids** [comment]
Ditto here on windows

**Comment by anrras** [comment]
same here in windows

**Comment by Kortantic** [comment]
JarmoCluyse's PR resolves the problem for me.
