### ISSUE TITLE
no test found.

### ISSUE THREAD

**Issue by vekexasia** [marilari88/neotest-vitest#68]
Are there any requirement for neotest-vitest to find tests? 

i am trying with a pretty complicated turborepo which runs vitest just fine but this seems to be unable to find my test cases..

I am currently trying with the [In source tests ](https://vitest.dev/guide/in-source) and using `:Neotest run`

**Comment by hinogi** [comment]
I have a nx monorepo, when I start nvim from the workspace root, tests are found but only the root config is used so the found tests all fail.
when  I start nvim from one of the actual project folders, no tests are found.
I use vitest for testing and the neotest-vitest adapter. I cannot see what files are searched and where or what vite, vitest config might be infolved

**Comment by benelan** [comment]
I was having the same problem and resolved it in #70. Can you test [my fork](https://github.com/benelan/neotest-vitest) to see if it resolves your issues as well?

**Comment by vekexasia** [comment]
@benelan I'd love to but i am a bit of a noob in neovim .... if you can tell me how to install your fork via lazy.nvim I'd be happy to try it out

**Comment by benelan** [comment]
Just change `marilari88/neotest-vitest` to `benelan/neotest-vitest` in your lazy spec

**Comment by vekexasia** [comment]
seems to be working fine... will report in case i find some tests not working
